name: Banco de Dados Backup Diário

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Executar Dump do Banco
        run: |
          pg_dump "${{ secrets.DB_CONNECTION_STRING }}?sslmode=require" | gzip > backup_render.sql.gz

      - name: Salvar Backup como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: backup-do-dia-${{ github.run_id }}
          path: backup_render.sql.gz
          retention-days: 30
